### ISSUE TITLE
ui overlapping of remove button on movie widget

### ISSUE THREAD

**Issue by spielhoelle** [ayhamk94/Devugees-Dashboard#55]
<img width="712" alt="screen shot 2017-12-19 at 12 41 26" src="https://user-images.githubusercontent.com/6317641/34155528-fb2803c4-e4b9-11e7-8aaf-c0439e35f5ee.png">

**Comment by oliverwebr** [comment]
ayham will resolve the "sausage finger accessibility" issue

**Comment by ayhamk94** [comment]
I fixed the overlapping
